### PR TITLE
fix(markdown): trimming styled text

### LINKED ISSUE #208: Trailing space in style block results in misrendered markdown
Within DraftJS, if I have a string such as ' foo ' styled entirely bold, exporting this to markdown will output `** foo **` which due to the surrounding whitespaces, results in `** foo **` being rendered rather than **foo**. 

[Similar issues occur](https://marked.js.org/demo/?text=**%20foo%20**%0A%0A**foo**%0A%0A**foo%20**%0A%0A*foo%20*bar%0A%0A*%20foo*%0A%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.8.0) when the whitespace is only on one end of the string.

I'm thinking that such styled strings should be trimmed and any whitespace be pushed to outside of the formatting syntax such that it can be rendered correctly. I can push a PR up shortly.

### PR DESCRIPTION
**Pull request by ashbrowning**
Resolves #208

If a word including its surrounding whitespace is formatted, the markdown output (while valid) will not correctly render the formatting.

### CODE REVIEW

**Comment by viococo** [comment]
Same issue here, I am interested by this PR. Looking forward to have it soon in a new release :)

**Comment by etiennecaldichouryatnapta** [comment]
Same here! Thanks for the fix!

File: packages/draft-js-export-markdown/src/stateToMarkdown.js [hunk 1]
```diff
@@ -218,13 +218,20 @@ class MarkupGenerator {
...
+            const rightPad = contentLength - content.length - leftPad;
+
             // NOTE: We attempt some basic character escaping here, although
             // I don't know if escape sequences are really valid in markdown,
             // there's not a canonical spec to lean on.
             if (style.has(CODE)) {
               return '`' + encodeCode(content) + '`';
             }
-            content = encodeContent(text);
+            content = encodeContent(text.trim());
```
Comment (tappleby) [inline packages/draft-js-export-markdown/src/stateToMarkdown.js]: Ran into some formatting issues with this if the trimmed result was a blank string, had to wrap the style logic in an additional length check. Also since the start / end are already trimmed above switched this to use `content` instead of `text`.

Comment (sstur) [reply packages/draft-js-export-markdown/src/stateToMarkdown.js]: Good catch!
```suggestion
            content = encodeContent(content);
```

File: packages/draft-js-export-markdown/src/stateToMarkdown.js [hunk 2]
```diff
@@ -218,13 +218,20 @@ class MarkupGenerator {
             if (blockType === BLOCK_TYPE.CODE) {
               return content;
             }
+
+            const contentLength = content.length;
+            content = content.trimLeft();
+            const leftPad = contentLength - content.length;
+            content = content.trimRight();
+            const rightPad = contentLength - content.length - leftPad;
+
```
Comment (sstur) [inline packages/draft-js-export-markdown/src/stateToMarkdown.js:231]:
```suggestion
if (!content.length) {
  // Return the original text if there is nothing left after trimming.
  return text;
}

```

**Review by sstur — APPROVED** [review]
This looks good. Thanks @ashbrowning!

**Comment by sstur** [comment]
Since the output `** foo **` is technically valid, we should probably fix this on the render side, rather than on the markdown creation side.

But for now this seems like a good workaround, so I'll merge this.
